Repository se2024-jpg/WolfTrack6.0, pull requests merged in 2024-11, with the labels that each got.

#31 Fix code scanning alert no. 1: DOM text reinterpreted as HTML
  templates/resume_builder_index.html
Labels: priority-medium, security-issue

#30 Fix code scanning alert no. 8: Information exposure through an exception
  app.py
Labels: priority-medium, security-issue

#33 Backend enhancements - Send_email related scripts
  Controller/ResumeParser.py
  Controller/data.py
  Controller/send_email.py
  Controller/send_profile.py
Labels: enhancement, priority-high

#32 14 issue build automated build and test from workflow are failing
  .github/workflows/main.yml
  .github/workflows/unit_test.yml
  UnitTesting/test_app.py
Labels: bug, priority-medium

#34 Modifying index.html
  templates/index.html
  templates/login.html
  templates/signup.html
Labels: enhancement, priority-medium

#35 Adding Test For Missing Required Fields on Signup
  UnitTesting/test_app.py
Labels: enhancement, priority-medium

#36 Feature/new testcases
  UnitTesting/test_app.py
Labels: bug, priority-medium

#40 Fixing DB security vulneribilites
  .gitignore
  app.py
  requirements.txt
Labels: priority-critical

#43 Feature/new testcases
  UnitTesting/database.db
  UnitTesting/test_app.py
Labels: enhancement, priority-medium

#44 Fixing test_registration_form_validation test case
  UnitTesting/test_app.py
Labels: enhancement, priority-medium

#45 Feature/new testcases
  UnitTesting/test_dbutils.py
  UnitTesting/test_jobprofileutils.py
  UnitTesting/test_loginutils.py
Labels: enhancement, priority-medium
